name 'df_box_elkstack'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures df_box_elkstack'
long_description 'Installs/Configures df_box_elkstack'
version '0.1.0'

depends 'df_java'
depends 'apt'
depends 'ark'
# depends 'df_elasticsearch'
# depends 'df_logstash'
# depends 'df_kibana'